[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "../engine" }

[dependencies.sdl2]
git = "https://github.com/Rust-SDL2/rust-sdl2"
rev = "76748c5"
default-features = false
features = ["ttf","image","gfx","mixer"]
